---
volumes:
  db_data:

services:
  db:
    image: postgres:alpine
    volumes:
      - "db_data:/var/lib/postgresql/data/pgdata"
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
